Strictly formatting cleanup

diff --git a/tools/procServMgr/procServMgr b/tools/procServMgr/procServMgr
--- a/tools/procServMgr/procServMgr
+++ b/tools/procServMgr/procServMgr
@@ -54,72 +54,72 @@ BINARY_LIST="$HOSTNAME $ID $APP_EXE"
 # Global Functions
 #-----------------------------------------------------------------------
 function usage {
-	echo "usage: $SCRIPT_NAME [-h] [-i iocname] start|stop|restart|check|status|test"
+    echo "usage: $SCRIPT_NAME [-h] [-i iocname] start|stop|restart|check|status|test"
     echo ""
-	echo "[-i] Specify the ioc. If not specified, the script assumes all iocs"
-	echo "[-c] Specify the configuration file."
-	echo "[-h] Print Help"
-	echo ""
-	echo "start      - start iocs specified in config file"
-	echo "stop       - stop iocs specified in config file"
-	echo "check      - start any iocs not running that are configured to run"
-	echo "restart    - stop and start iocs specified in config file"
-	echo "status     - dump a short status screen showing current status"
-	echo "test       - show how each IOC would be invoked but don't do anything"
-	echo ""
-	echo "Examples:"
-	echo "$SCRIPT_NAME start  - start all iocs enabled in the config file"
-	echo "$SCRIPT_NAME stop   - stop all iocs enabled in the config file"
-	echo "$SCRIPT_NAME status - show status for all iocs"
-	echo "$SCRIPT_NAME -c /tmp/testconfig.conf check - use alternate config file"
-	echo "$SCRIPT_NAME -i iocsofthrt start - start ioc iocsofthrt only"
-	echo "$SCRIPT_NAME -i iocsofthrt test - show  start command for iocsofthrt"
-	echo ""
-	echo "CONFIGURATION FILES:"
-	echo "--------------------"
+    echo "[-i] Specify the ioc. If not specified, the script assumes all iocs"
+    echo "[-c] Specify the configuration file."
+    echo "[-h] Print Help"
+    echo ""
+    echo "start      - start iocs specified in config file"
+    echo "stop       - stop iocs specified in config file"
+    echo "check      - start any iocs not running that are configured to run"
+    echo "restart    - stop and start iocs specified in config file"
+    echo "status     - dump a short status screen showing current status"
+    echo "test       - show how each IOC would be invoked but don't do anything"
+    echo ""
+    echo "Examples:"
+    echo "$SCRIPT_NAME start  - start all iocs enabled in the config file"
+    echo "$SCRIPT_NAME stop   - stop all iocs enabled in the config file"
+    echo "$SCRIPT_NAME status - show status for all iocs"
+    echo "$SCRIPT_NAME -c /tmp/testconfig.conf check - use alternate config file"
+    echo "$SCRIPT_NAME -i iocsofthrt start - start ioc iocsofthrt only"
+    echo "$SCRIPT_NAME -i iocsofthrt test - show  start command for iocsofthrt"
+    echo ""
+    echo "CONFIGURATION FILES:"
+    echo "--------------------"
 
-	for FILE in $FILE_LIST 	
-		do
-		echo $FILE
-		done
-	
-	echo ""
-	
-	printhostconfig
+    for FILE in $FILE_LIST     
+        do
+        echo $FILE
+        done
+    
+    echo ""
+    
+    printhostconfig
 }
 
 function checkfile {
-	if [ ! -f $1 ]; then
-		echo "Could not find file: $1" 
-		exit 1
-	fi
+    if [ ! -f $1 ]; then
+        echo "Could not find file: $1" 
+        exit 1
+    fi
 }
 
 function checkdir {
-	if [ ! -d $1 ]; then
-		echo "Could not find directory: $1" 
-		exit 1
-	fi
-}	
+    if [ ! -d $1 ]; then
+        echo "Could not find directory: $1" 
+        exit 1
+    fi
+}    
 
 
 function parseconfig {
-	i=0
-	e=0
-	d=0
-	h=0
+    i=0
+    e=0
+    d=0
+    h=0
 
-	IFS=":"
-	while read  iocname computer port status stcmd options start_options
-	do
-		if [ "`echo $iocname | cut -c1`" = "#" ] ; then
-		# Skip comments
-		continue
-		fi
-		if [ "`echo $iocname | cut -c1`" = "" ] ; then
-			# Skip blank lines
-			continue
-		fi
+    IFS=":"
+    while read  iocname computer port status stcmd options start_options
+    do
+        if [ "`echo $iocname | cut -c1`" = "#" ] ; then
+        # Skip comments
+        continue
+        fi
+        if [ "`echo $iocname | cut -c1`" = "" ] ; then
+            # Skip blank lines
+            continue
+        fi
           
         #remove white space at start and end and only accept a single string
         iocname=`echo "$iocname" | sed 's/^[ \t]*//;s/[ \t]*$//' | awk '{print $1}'`
@@ -131,158 +131,158 @@ function parseconfig {
         #remove white space at start and end
         options=`echo "$options" | sed 's/^[ \t]*//;s/[ \t]*$//'`
         start_options=`echo "$start_options" | sed 's/^[ \t]*//;s/[ \t]*$//'`
-		            
-		export ${iocname}_host="$computer"    
-		export ${iocname}_port="$port"
-		export ${iocname}_stcmd="$stcmd"
-		export ${iocname}_options="$options"
-		export ${iocname}_start_options="$start_options"
+                    
+        export ${iocname}_host="$computer"    
+        export ${iocname}_port="$port"
+        export ${iocname}_stcmd="$stcmd"
+        export ${iocname}_options="$options"
+        export ${iocname}_start_options="$start_options"
 
-		iocs[$i]=$iocname
-		((i=i+1)) 
+        iocs[$i]=$iocname
+        ((i=i+1)) 
 
-		case $status in
-			enable|enabled|on)
-				iocs_enabled[$e]=$iocname  
-				((e=e+1))
-				export ${iocname}_status=enabled
-				;;
-			*)
-				iocs_disabled[$d]=$iocname   
-				((d=d+1))
-				export ${iocname}_status=disabled
-		esac
+        case $status in
+            enable|enabled|on)
+                iocs_enabled[$e]=$iocname  
+                ((e=e+1))
+                export ${iocname}_status=enabled
+                ;;
+            *)
+                iocs_disabled[$d]=$iocname   
+                ((d=d+1))
+                export ${iocname}_status=disabled
+        esac
 
-		if [ "$computer" = "$HOST" ] ; then
-			iocs_host[$h]=$iocname
-			((h=h+1))
-		fi
-	done < $CONFIG_FILE
-	unset IFS
+        if [ "$computer" = "$HOST" ] ; then
+            iocs_host[$h]=$iocname
+            ((h=h+1))
+        fi
+    done < $CONFIG_FILE
+    unset IFS
 }
 
 function printconfig {
-	echo "IOC CONFIGURATION"
-	echo "-----------------"
-	for i in ${iocs[*]}
-		do
-		#echo IOC configured STATUS to run HOST:PORT
-		echo "$i $(eval echo \$${i}_status) to run on $(eval echo \$${i}_host):$(eval echo \$${i}_port)"
-		done
-	echo ""
+    echo "IOC CONFIGURATION"
+    echo "-----------------"
+    for i in ${iocs[*]}
+        do
+        #echo IOC configured STATUS to run HOST:PORT
+        echo "$i $(eval echo \$${i}_status) to run on $(eval echo \$${i}_host):$(eval echo \$${i}_port)"
+        done
+    echo ""
 }
 
 function printcommands {
     echo "IOC START COMMANDS"
-	echo "------------------"
-	for i in ${iocs[*]} do
-		OPTIONS="$(eval echo \$${i}_options)"
-		START_OPTIONS="$(eval echo \$${i}_start_options)"
-		PORT="$(eval echo \$${i}_port)"
-		STCMD="$(eval echo \$${i}_stcmd)"
-		echo "$APP_EXE $OPTIONS -n $i -i^D^C -c $IOC_DIR/$i $PORT $STCMD $START_OPTIONS >/dev/null 2>&1"  
-		done
-	echo ""
+    echo "------------------"
+    for i in ${iocs[*]} do
+        OPTIONS="$(eval echo \$${i}_options)"
+        START_OPTIONS="$(eval echo \$${i}_start_options)"
+        PORT="$(eval echo \$${i}_port)"
+        STCMD="$(eval echo \$${i}_stcmd)"
+        echo "$APP_EXE $OPTIONS -n $i -i^D^C -c $IOC_DIR/$i $PORT $STCMD $START_OPTIONS >/dev/null 2>&1"  
+        done
+    echo ""
 }
 
 function printhostconfig {
-	echo "IOC CONFIGURED FOR $HOST"
-	echo "--------------------------"
-	
-	if [ "${iocs_host[*]}" != "" ]; then
-		for i in ${iocs_host[*]} do
-			#echo IOC configured STATUS to run HOST:PORT
-			echo "$i $(eval echo \$${i}_status) to run on $(eval echo \$${i}_host):$(eval echo \$${i}_port)"
-			done
-	else
-		echo "No iocs are configured to run on $HOST"	
-	fi
+    echo "IOC CONFIGURED FOR $HOST"
+    echo "--------------------------"
+    
+    if [ "${iocs_host[*]}" != "" ]; then
+        for i in ${iocs_host[*]} do
+            #echo IOC configured STATUS to run HOST:PORT
+            echo "$i $(eval echo \$${i}_status) to run on $(eval echo \$${i}_host):$(eval echo \$${i}_port)"
+            done
+    else
+        echo "No iocs are configured to run on $HOST"    
+    fi
 
-	echo ""
+    echo ""
 }
 
 function start_ioc {
-	if [ ! -d $IOC_DIR/$1 ]; then
-		echo "Could not start $1 - no directory $IOC_DIR/$1" 
-		return 1
-	fi
-	 
-	STCMD="$(eval echo \$${i}_stcmd)"
-	OPTIONS="$(eval echo \$${i}_options)"
-	START_OPTIONS="$(eval echo \$${i}_start_options)"
-	processfound="`ps -ef | grep -v grep | grep $1 | grep $2 | awk '{print $2}'`"
-    if [ "$processfound" != "" ] ; then
-	 	echo "Could not start $1 - $1 is already running with pid $processfound" 
+    if [ ! -d $IOC_DIR/$1 ]; then
+        echo "Could not start $1 - no directory $IOC_DIR/$1" 
         return 1
-	fi
+    fi
+     
+    STCMD="$(eval echo \$${i}_stcmd)"
+    OPTIONS="$(eval echo \$${i}_options)"
+    START_OPTIONS="$(eval echo \$${i}_start_options)"
+    processfound="`ps -ef | grep -v grep | grep $1 | grep $2 | awk '{print $2}'`"
+    if [ "$processfound" != "" ] ; then
+         echo "Could not start $1 - $1 is already running with pid $processfound" 
+        return 1
+    fi
     
-	$APP_EXE $OPTIONS -n $1 -i^D^C -c $IOC_DIR/$1 $2 $STCMD $START_OPTIONS >/dev/null 2>&1
+    $APP_EXE $OPTIONS -n $1 -i^D^C -c $IOC_DIR/$1 $2 $STCMD $START_OPTIONS >/dev/null 2>&1
  
-	if [ $? != 0 ]; then
-		echo "Could not start $1 on port $2 of $HOST"
-	 	return 1
-	else 
-		echo "Started $1 on port $2 of $HOST  `date`"	 
-	 	return 0
-	fi
+    if [ $? != 0 ]; then
+        echo "Could not start $1 on port $2 of $HOST"
+         return 1
+    else 
+        echo "Started $1 on port $2 of $HOST  `date`"     
+         return 0
+    fi
 }
 
 function test_ioc {
-	STCMD="$(eval echo \$${i}_stcmd)"
-	OPTIONS="$(eval echo \$${i}_options)"
-	START_OPTIONS="$(eval echo \$${i}_start_options)"
-	echo "$APP_EXE $OPTIONS -n $1 -i^D^C -c $IOC_DIR/$1 $2 $STCMD $START_OPTIONS >/dev/null 2>&1"           
-	return 0
+    STCMD="$(eval echo \$${i}_stcmd)"
+    OPTIONS="$(eval echo \$${i}_options)"
+    START_OPTIONS="$(eval echo \$${i}_start_options)"
+    echo "$APP_EXE $OPTIONS -n $1 -i^D^C -c $IOC_DIR/$1 $2 $STCMD $START_OPTIONS >/dev/null 2>&1"           
+    return 0
 }
 
 
 function stop_ioc {
-	processfound="`ps -ef | grep -v grep | grep $1 | grep $2 | awk '{print $2}'`"
-	
-	if [ "$processfound" != "" ]; then
-		kill -9 $processfound
-		if [ $? != 0 ]; then
-			return 1
-		else
-			echo "killed $1 on port $2 with pid $processfound"
-			return 0
-		fi
-	else
-		return 1
-	fi
+    processfound="`ps -ef | grep -v grep | grep $1 | grep $2 | awk '{print $2}'`"
+    
+    if [ "$processfound" != "" ]; then
+        kill -9 $processfound
+        if [ $? != 0 ]; then
+            return 1
+        else
+            echo "killed $1 on port $2 with pid $processfound"
+            return 0
+        fi
+    else
+        return 1
+    fi
 }
 
 function status_ioc {
-	if [ "$(eval echo \$${i}_status)" = "enabled" ]; then
-		processfound="`ps -ef | grep -v grep | grep $1 | grep $2 | awk '{print $2}'`"
-		if [ "$processfound" != "" ] ; then
-			echo "$1 running on port $2 of $HOST with pid $processfound"
-		else
-			echo "$1 NOT running on port $2 of $HOST"
-		fi
-	else
-		echo "$1 is disabled from running on port $2 of $HOST"
-	fi
-}	
+    if [ "$(eval echo \$${i}_status)" = "enabled" ]; then
+        processfound="`ps -ef | grep -v grep | grep $1 | grep $2 | awk '{print $2}'`"
+        if [ "$processfound" != "" ] ; then
+            echo "$1 running on port $2 of $HOST with pid $processfound"
+        else
+            echo "$1 NOT running on port $2 of $HOST"
+        fi
+    else
+        echo "$1 is disabled from running on port $2 of $HOST"
+    fi
+}    
 
 function check_ioc {
-	processfound="`ps -ef | grep -v grep | grep $1 | grep $2 | awk '{print $2}'`"
-	if [ "$processfound" != "" ] ; then
-		return 1
-	else
-		return 0
-	fi
+    processfound="`ps -ef | grep -v grep | grep $1 | grep $2 | awk '{print $2}'`"
+    if [ "$processfound" != "" ] ; then
+        return 1
+    else
+        return 0
+    fi
 }
 
 function checkuser {
-	SCRIPT_USER_ID=`$ID -u $SCRIPT_USER`
-	USER_ID=`$ID -u`
+    SCRIPT_USER_ID=`$ID -u $SCRIPT_USER`
+    USER_ID=`$ID -u`
 
-	if [ $USER_ID != $SCRIPT_USER_ID ]; then
-		echo "You must be $SCRIPT_USER to run $SCRIPT_NAME"
-	   	echo "Please use \"iam $SCRIPT_USER\" or \"sudo -u $SCRIPT_USER\" to run this script"
-	   	exit 1
-	fi
+    if [ $USER_ID != $SCRIPT_USER_ID ]; then
+        echo "You must be $SCRIPT_USER to run $SCRIPT_NAME"
+           echo "Please use \"iam $SCRIPT_USER\" or \"sudo -u $SCRIPT_USER\" to run this script"
+           exit 1
+    fi
 }
 
 #-----------------------------------------------------------------------
@@ -291,20 +291,20 @@ function checkuser {
 while getopts ":hc:i:" opt; do
     case $opt in
     c) 
-	 	CONFIG_FILE=$OPTARG	
-	   	FILE_LIST="$CONFIG_FILE"
-	   	for FILE in $FILE_LIST 	
-	   	do
-			checkfile $FILE
-	   	done	
-	   	;;   
+         CONFIG_FILE=$OPTARG    
+           FILE_LIST="$CONFIG_FILE"
+           for FILE in $FILE_LIST     
+           do
+            checkfile $FILE
+           done    
+           ;;   
     i) 
         OPT_IOC=$OPTARG
-	   	;;	
-	h) 
-		OPT_HELP=1
-	   	;;
-   	\?)
+           ;;    
+    h) 
+        OPT_HELP=1
+           ;;
+       \?)
         OPT_UNKNOWN=$OPTARG  
         ;;
     *) 
@@ -324,169 +324,167 @@ shift $(($OPTIND - 1))
 parseconfig
 
 if [ "$OPT_HELP" ]; then
-	usage
+    usage
     exit 0
 fi
 
 if [ "$OPT_UNKNOWN" ]; then
-	echo "Unknown Option: $OPT_UNKNOWN"
+    echo "Unknown Option: $OPT_UNKNOWN"
     usage
     exit 1
 fi
 
 if [ -z "$1" ]; then
-	echo "You must specify an action!"
-	echo ""
-	usage
-	exit 1
+    echo "You must specify an action!"
+    echo ""
+    usage
+    exit 1
 fi
 
 if [ "$OPT_IOC" ]; then
-	ret=0
-	
-	for IOC in ${iocs_enabled[*]}		               
-	do
-		if [ $OPT_IOC = $IOC ]; then                
-		((ret=ret+1))
-	fi
-	done
+    ret=0
+    
+    for IOC in ${iocs_enabled[*]}                       
+    do
+        if [ $OPT_IOC = $IOC ]; then                
+        ((ret=ret+1))
+    fi
+    done
 
-	if [ $ret = 0 ]; then
-		echo ""
-		echo "$OPT_IOC is not enabled for $HOST in:" 
-		echo "     $CONFIG_FILE"
-		echo "You may need to update this file before continuing"
-		echo ""
-		printconfig
-		echo ""
-		exit 1
-	fi
-	set -A iocs_enabled $OPT_IOC
-	set -A iocs_host $OPT_IOC
+    if [ $ret = 0 ]; then
+        echo ""
+        echo "$OPT_IOC is not enabled for $HOST in:" 
+        echo "     $CONFIG_FILE"
+        echo "You may need to update this file before continuing"
+        echo ""
+        printconfig
+        echo ""
+        exit 1
+    fi
+    set -A iocs_enabled $OPT_IOC
+    set -A iocs_host $OPT_IOC
 fi
 
 #-----------------------------------------------------------------------
 # Data File Sanity Check
 #-----------------------------------------------------------------------
-for DIR in $DIR_LIST	
+for DIR in $DIR_LIST    
 do
-	checkdir $DIR
+    checkdir $DIR
 done
-	
-for FILE in $FILE_LIST 	
+    
+for FILE in $FILE_LIST     
 do
-	checkfile $FILE
-done		
+    checkfile $FILE
+done        
 
-for BINARY in $BINARY_LIST 	
+for BINARY in $BINARY_LIST     
 do
-	checkfile $FILE
+    checkfile $FILE
 done
 
 #-----------------------------------------------------------------------
 # Main Routine
 #-----------------------------------------------------------------------
 if [ "$1" = "test" ]; then
-	echo ""
+    echo ""
     printconfig
 fi
 
 if [ "${iocs_host[*]}" != "" ]; then
-	for i in ${iocs_host[*]}
-	do
-		if [ "$(eval echo \$${i}_status)" = "enabled" ]; then
-		
-		#See how we were called.
-		case "$1" in
-		start)
-			checkuser
-			start_ioc $i $(eval echo \$${i}_port)	
-			;;
-		stop)
-			checkuser
-			stop_ioc $i $(eval echo \$${i}_port)
-			;;
-		restart)
-			checkuser
-			stop_ioc  $i $(eval echo \$${i}_port)
-			start_ioc $i $(eval echo \$${i}_port)
-			;;
-		status)
-			status_ioc  $i $(eval echo \$${i}_port)
-			;;
-		test)
-			test_ioc  $i $(eval echo \$${i}_port)
-			;;
-		check)
-			checkuser
-			check_ioc $i $(eval echo \$${i}_port)
-			if [ $? = 0 ]; then
-				start_ioc $i $(eval echo \$${i}_port)
-			fi
-			;;
-		*)
-			usage
-			exit 1
-			;;
-		esac
-
-		else
-			#See how we were called.
-			case "$1" in
-			start)
-				checkuser
-				;;
-			stop)
-				checkuser
-				stop_ioc $i $(eval echo \$${i}_port)
-				;;
-			restart)
-				checkuser
-				;;
-			status)
-				status_ioc  $i $(eval echo \$${i}_port)
-				stop_ioc $i $(eval echo \$${i}_port)
-				;;
-			test)
-				test_ioc  $i $(eval echo \$${i}_port)
-				;;
-			check)
-				checkuser
-				stop_ioc $i $(eval echo \$${i}_port)
-				;;
-			*)
-				usage
-				exit 1
-				;;
-			esac
-		fi
-	done
+    for i in ${iocs_host[*]}
+    do
+        if [ "$(eval echo \$${i}_status)" = "enabled" ]; then
+            #See how we were called.
+            case "$1" in
+            start)
+                checkuser
+                start_ioc $i $(eval echo \$${i}_port)    
+                ;;
+            stop)
+                checkuser
+                stop_ioc $i $(eval echo \$${i}_port)
+                ;;
+            restart)
+                checkuser
+                stop_ioc  $i $(eval echo \$${i}_port)
+                start_ioc $i $(eval echo \$${i}_port)
+                ;;
+            status)
+                status_ioc  $i $(eval echo \$${i}_port)
+                ;;
+            test)
+                test_ioc  $i $(eval echo \$${i}_port)
+                ;;
+            check)
+                checkuser
+                check_ioc $i $(eval echo \$${i}_port)
+                if [ $? = 0 ]; then
+                    start_ioc $i $(eval echo \$${i}_port)
+                fi
+                ;;
+            *)
+                usage
+                exit 1
+                ;;
+            esac
+        else
+            #See how we were called.
+            case "$1" in
+            start)
+                checkuser
+                ;;
+            stop)
+                checkuser
+                stop_ioc $i $(eval echo \$${i}_port)
+                ;;
+            restart)
+                checkuser
+                ;;
+            status)
+                status_ioc  $i $(eval echo \$${i}_port)
+                stop_ioc $i $(eval echo \$${i}_port)
+                ;;
+            test)
+                test_ioc  $i $(eval echo \$${i}_port)
+                ;;
+            check)
+                checkuser
+                stop_ioc $i $(eval echo \$${i}_port)
+                ;;
+            *)
+                usage
+                exit 1
+                ;;
+            esac
+        fi
+    done
 else
-	#echo "No iocs are configured to run on $HOST"
-	case "$1" in
-	start)
-		echo "No iocs are configured to run on $HOST"
-		;;
-	stop)
-		echo "No iocs are configured to run on $HOST"
-		;;
-	restart)
-		echo "No iocs are configured to run on $HOST"
-		;;
-	status)
-		echo "No iocs are configured to run on $HOST"
-		;;
-	test)
-		echo "No iocs are configured to run on $HOST"
-		;;
-	check)
-		continue
-		;;
-	*)
-		usage
-		exit 1
-		;;
-	esac	
+    #echo "No iocs are configured to run on $HOST"
+    case "$1" in
+    start)
+        echo "No iocs are configured to run on $HOST"
+        ;;
+    stop)
+        echo "No iocs are configured to run on $HOST"
+        ;;
+    restart)
+        echo "No iocs are configured to run on $HOST"
+        ;;
+    status)
+        echo "No iocs are configured to run on $HOST"
+        ;;
+    test)
+        echo "No iocs are configured to run on $HOST"
+        ;;
+    check)
+        continue
+        ;;
+    *)
+        usage
+        exit 1
+        ;;
+    esac    
 fi
 
 exit 0
diff --git a/tools/procServMgr/softioc_console b/tools/procServMgr/softioc_console
--- a/tools/procServMgr/softioc_console
+++ b/tools/procServMgr/softioc_console
@@ -55,57 +55,57 @@ BINARY_LIST="$HOSTNAME $ID $TELNET $SSH $APP_EXE"
 # Global Functions
 #-----------------------------------------------------------------------
 function usage {
-	echo "usage: $SCRIPT_NAME [-h] iocname"
+    echo "usage: $SCRIPT_NAME [-h] iocname"
     echo ""
-	echo "[-h] Print Help"
-	echo ""
-	echo "Examples:"
-	echo "$SCRIPT_NAME [-h]"
-	echo "$SCRIPT_NAME iocsofthrt - start a console on ioc iocsofthrt"
-	echo ""
-	echo "CONFIGURATION FILES:"
-	echo "--------------------"
-	for FILE in $FILE_LIST 	
-	do
-		echo $FILE
-	done
-	
-	echo ""
+    echo "[-h] Print Help"
+    echo ""
+    echo "Examples:"
+    echo "$SCRIPT_NAME [-h]"
+    echo "$SCRIPT_NAME iocsofthrt - start a console on ioc iocsofthrt"
+    echo ""
+    echo "CONFIGURATION FILES:"
+    echo "--------------------"
+    for FILE in $FILE_LIST     
+    do
+        echo $FILE
+    done
+    
+    echo ""
 
-	printconfig
+    printconfig
 }
 
 function checkfile {
-	if [ ! -f $1 ];then
-		echo "Could not find file $1" 
-		exit 1
-	fi
+    if [ ! -f $1 ];then
+        echo "Could not find file $1" 
+        exit 1
+    fi
 }
 
 function checkdir {
-	if [ ! -d $1 ];then
-		echo "Could not find directory $1" 
-		exit 1
-	fi
-}	
+    if [ ! -d $1 ];then
+        echo "Could not find directory $1" 
+        exit 1
+    fi
+}    
 
 function parseconfig {
-	i=0
-	e=0
-	d=0
-	h=0
+    i=0
+    e=0
+    d=0
+    h=0
 
-	IFS=":"
-	while read  iocname computer port status options start_options
-	do
-		if [ "`echo $iocname | cut -c1`" = "#" ] ; then
-		# Skip comments
-		continue
-		fi
-		if [ "`echo $iocname | cut -c1`" = "" ] ; then
-		# Skip blank lines
-		continue
-		fi
+    IFS=":"
+    while read  iocname computer port status options start_options
+    do
+        if [ "`echo $iocname | cut -c1`" = "#" ] ; then
+        # Skip comments
+        continue
+        fi
+        if [ "`echo $iocname | cut -c1`" = "" ] ; then
+        # Skip blank lines
+        continue
+        fi
           
           #remove white space at start and end and only accept a single string
           iocname=`echo "$iocname"   | sed 's/^[ \t]*//;s/[ \t]*$//'| awk '{print $1}'`
@@ -118,70 +118,66 @@ function parseconfig {
           options=`echo "$options" | sed 's/^[ \t]*//;s/[ \t]*$//'`
           start_options=`echo "$start_options" | sed 's/^[ \t]*//;s/[ \t]*$//'`
           
-		#print $(eval echo \$${ioc}_port) 
-		export ${iocname}_host="$computer"    
-		export ${iocname}_port="$port"
-		export ${iocname}_options="$options"
-		export ${iocname}_start_options="$start_options"
+        #print $(eval echo \$${ioc}_port) 
+        export ${iocname}_host="$computer"    
+        export ${iocname}_port="$port"
+        export ${iocname}_options="$options"
+        export ${iocname}_start_options="$start_options"
 
-		#export ${iocname}_status=$options
+        #export ${iocname}_status=$options
 
-		iocs[$i]=$iocname
-		((i=i+1)) 
+        iocs[$i]=$iocname
+        ((i=i+1)) 
 
-		case $status in
-		enable|enabled|on)
-			iocs_enabled[$e]=$iocname  
-			((e=e+1))
-			export ${iocname}_status=enabled
-		;;
-		*)
-			iocs_disabled[$d]=$iocname   
-			((d=d+1))
-			export ${iocname}_status=disabled
-		esac
+        case $status in
+        enable|enabled|on)
+            iocs_enabled[$e]=$iocname  
+            ((e=e+1))
+            export ${iocname}_status=enabled
+        ;;
+        *)
+            iocs_disabled[$d]=$iocname   
+            ((d=d+1))
+            export ${iocname}_status=disabled
+        esac
 
-		if [ "$computer" = "$HOST" ] ; then
-		iocs_host[$h]=$iocname
-		((h=h+1))
-		fi
-
-	done < $CONFIG_FILE
-unset IFS
+        if [ "$computer" = "$HOST" ] ; then
+        iocs_host[$h]=$iocname
+        ((h=h+1))
+        fi
+    done < $CONFIG_FILE
+	unset IFS
 }
 
 function printconfig {
-
-	echo "IOC CONFIGURATION"
-	echo "-----------------"
-	for i in ${iocs[*]}
-		do
-		#echo IOC configured STATUS to run HOST:PORT
-		echo "$i $(eval echo \$${i}_status) to run on $(eval echo \$${i}_host):$(eval echo \$${i}_port)"
-		done
-	echo ""
-
+    echo "IOC CONFIGURATION"
+    echo "-----------------"
+    for i in ${iocs[*]}
+        do
+        #echo IOC configured STATUS to run HOST:PORT
+        echo "$i $(eval echo \$${i}_status) to run on $(eval echo \$${i}_host):$(eval echo \$${i}_port)"
+        done
+    echo ""
 }
 
 
 #-----------------------------------------------------------------------
 # Process Options
 #-----------------------------------------------------------------------
-
 parseconfig
 
 while getopts ":h:" opt; do
     case $opt in
         
-	h) usage 
-	   return 0
-	   ;;
+    h) usage 
+       return 0
+       ;;
        \?) echo "Unknown Option: $opt"
-       	   usage
+              usage
            return 0
            ;;
         *) echo "Unknown Option: $opt"
-	   usage
+       usage
            return 1
                 ;;      
     esac
@@ -193,84 +189,78 @@ done
 shift $(($OPTIND - 1))
 
 if [ -z "$1" ]; then
-	echo "You must specify an ioc"
-	echo ""
-	usage
-	exit 1
+    echo "You must specify an ioc"
+    echo ""
+    usage
+    exit 1
 fi
 
 #-----------------------------------------------------------------------
 # Data File Sanity Check
 #-----------------------------------------------------------------------
+for DIR in $DIR_LIST    
+    do
+    checkdir $DIR
+    done
+    
+for FILE in $FILE_LIST     
+    do
+    checkfile $FILE
+    done        
 
-for DIR in $DIR_LIST	
-	do
-	checkdir $DIR
-	done
-	
-for FILE in $FILE_LIST 	
-	do
-	checkfile $FILE
-	done		
-
-for BINARY in $BINARY_LIST 	
-	do
-	checkfile $FILE
-	done
+for BINARY in $BINARY_LIST     
+    do
+    checkfile $FILE
+    done
 
 #-----------------------------------------------------------------------
 # Main Routine
 #-----------------------------------------------------------------------
-
-
 ret=0
 for IOC in ${iocs_disabled[*]}
-do	
-if [ $1 = $IOC ]; then                
-((ret=ret+1))
-fi
+do    
+    if [ $1 = $IOC ]; then
+        ((ret=ret+1))
+    fi
 done
 
 if [ $ret = 1 ]; then
-echo ""
-echo "$1 was found disabled in the configuration file" 
-echo "     $CONFIG_FILE"
-echo "You may need to update this file before continuing"
-echo ""
-printconfig
-echo ""
-exit 1
+    echo ""
+    echo "$1 was found disabled in the configuration file" 
+    echo "     $CONFIG_FILE"
+    echo "You may need to update this file before continuing"
+    echo ""
+    printconfig
+    echo ""
+    exit 1
 fi
 
 ret=0
 for IOC in ${iocs_enabled[*]}
-do	
-if [ $1 = $IOC ]; then                
-((ret=ret+1))
-fi
+do    
+    if [ $1 = $IOC ]; then                
+        ((ret=ret+1))
+    fi
 done
 
 
 if [ $ret = 0 ]; then
-echo ""
-echo "$1 was not found in the configuration file" 
-echo "     $CONFIG_FILE"
-echo "You may need to update this file before continuing"
-echo ""
-printconfig
-echo ""
-exit 1
+    echo ""
+    echo "$1 was not found in the configuration file" 
+    echo "     $CONFIG_FILE"
+    echo "You may need to update this file before continuing"
+    echo ""
+    printconfig
+    echo ""
+    exit 1
 fi
-	  
-
-#echo "$HOST"
-#echo "$(eval echo \$${ioc}_host)"
+      
 if [ "$(eval echo \$${1}_host)" = "$HOST" ] ; then
-echo "$TELNET localhost $(eval echo \$${1}_port)"
-$TELNET localhost $(eval echo \$${1}_port)
+    echo "$TELNET localhost $(eval echo \$${1}_port)"
+    $TELNET localhost $(eval echo \$${1}_port)
 else
-echo $SSH "$(eval echo \$${1}_host)" $TELNET localhost $(eval echo \$${1}_port)
-$SSH "$(eval echo \$${1}_host)" $TELNET localhost $(eval echo \$${1}_port)
+    echo $SSH "$(eval echo \$${1}_host)" $TELNET localhost $(eval echo \$${1}_port)
+    $SSH "$(eval echo \$${1}_host)" $TELNET localhost $(eval echo \$${1}_port)
 fi
 
 exit 0
